# Generated by Django 3.0.4 on 2020-03-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodapp', '0003_signupforms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupForms',
        ),
    ]
