# Generated by Django 3.0.4 on 2020-03-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodapp', '0008_profile_neighbourhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='updates',
        ),
    ]
