# Generated by Django 3.0.4 on 2020-03-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodapp', '0009_auto_20200326_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighbourhood',
            options={'ordering': ['name']},
        ),
    ]
